### ISSUE TITLE
Create template files

### ISSUE THREAD

**Issue by Stophface** [Stophface/react-native-maps-0.20.1#1]
In order to implement the offline maps, files into which the code is written must be written. The files from `LocalTileOverlay` will be used as "template" files. In order to do this, they must be duplicated and successfully integrated into the project.

**Comment by Stophface** [comment]
Where do I "register" the files I created. I now have `MapView.js`, `MapMbTile.js`, `AIRMapMbTileManager.h` and `AIRMapMbTileManager.h`.  See commit https://github.com/Stophface/react-native-maps-0.20.1/commit/045aee99e4d360734cb2fc60ccdf4bdab5ab0171


When I try something like 
    
    ...
    <MapView>
          <MbTile />
    </MapView>
    ...

I get a reference error

> ReferenceError: Can't find variable MbTile.

Although I named it like this in `MapMbTile.js`

```
export default decorateMapComponent(MapMbTile, {
  componentType: 'MbTile',
  providers: {
    google: {
      ios: SUPPORTED,
      android: USES_DEFAULT_IMPLEMENTATION,
    },
  },
});
```

and included it into `MapView.js`

```
import MapMbTile from './MapMbTile';
...
MapView.MbTile = MapMbTile;
```

I guess somehow I must make `<MbTile />` known to `react-native`?

**Comment by zavadpe** [comment]
What platform are you running example on? I had similar issues on iOS and I needed clean rebuild library project for the new component to take effect.

**Comment by Stophface** [comment]
@zavadpe I updated the error... I am trying on iOS first. With clean rebuild you mean `yarn install`?

**Comment by zavadpe** [comment]
@Stophface No, I mean when you run example using `npm build:ios` and `npm run:ios` there's pretty much behind the curtain. try to delete all produced files while building for ios and build again from the scratch.

**Comment by Stophface** [comment]
@zavadpe Ah alright. I will delete all the dependencies as soon as I solved this problem.

In my `package.json` I added these dependencies
```

  "dependencies": {
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0-rc.3",
    "react-native-maps": "https://github.com/Stophface/react-native-maps-0.20.1.git"
  },
```
When I check the repo *online* the files I created are there. However, when I make a `yarn install` the newly created files/changes are not in the `node_moduls/react-native-maps/...` folder.

**Comment by zavadpe** [comment]
@Stophface  Then you are doing something wrong because when I `npm install` https://github.com/Stophface/react-native-maps-0.20.1.git dependency those files sits in `node_moduls/react-native-maps/` folder just fine.

**Comment by Stophface** [comment]
@zavadpe Hm, I am on the level of the `package.json', I delete all the `node_modules` and then type `yarn install` (I have to use `yarn` because with the version of `react-native-maps` I am using `npm` won't work). As far as I am concerned that is how it should go. I also tried `yarn add https://github.com/Stophface/react-native-maps-0.20.1.git` but that did not do the trick neither. 
I will figure out why. That might take a bit.

**Comment by Stophface** [comment]
@zavadpe I got it working. Cleaning the build folder and buidling the project completly new did the trick. 

I still get this error though:

> Invariation violation: Element type is invalid: expected string (for built in components) or a
> class/function (for composite components) but got: undefined. You likely forgot to export your
> component from the file its defined in, or you might have mixed up default and named imports.
> Check the render method of App
> This error is located at
> AIRMap (at MapView.js765)
> in MapView(at App.js25)
...

I think the rest is uninteresting. 

`App.js25` is this line
    
```
return (
      <View
        style={styles.container}>
        <MapView
          style={styles.map}
          initialRegion={{
            latitude: LATITUDE,
            longitude: LONGITUDE,
            latitudeDelta: LATITUDE_DELTA,
            longitudeDelta: LONGITUDE_DELTA,
          }}
          loadingEnabled
          loadingIndicatorColor="#666666"
          loadingBackgroundColor="#eeeeee">
          <MbTile />
        </MapView>
      </View>
    )
```

While `MapView.js765` this is
```
return (
      <AIRMap
        ref={ref => { this.map = ref; }}
        {...props}
      />
```

**Comment by Stophface** [comment]
@zavadpe Did you add any files to XCode?
I basically duplicated all of your files and added them in the `AIRMap.m` as well as `MapView.js`.
When I try to compile I get

```
ld: warning: directory not found for option '-L/.../Developer/Xcode/DerivedData/maps-gbxkbflbczdvrtdqdwdpkbxyswgv/Build/Products/Debug-iphonesimulator/React'
ld: warning: object file (/Users/.../Developer/Xcode/DerivedData/maps-gbxkbflbczdvrtdqdwdpkbxyswgv/Build/Products/Debug-iphonesimulator/libPods-maps.a(Pods-maps-dummy.o)) was built for newer iOS version (9.0) than being linked (8.0)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AIRMapMbTile", referenced from:
      objc-class-ref in libreact-native-maps.a(AIRMap.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

"_OBJC_CLASS_$_AIRMapMbTile", referenced from:
objc-class-ref in libreact-native-maps.a(AIRMap.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I assume (not sure here) that I somewhere need to add some of the files to the XCode project. Did you do that?

**Comment by Stophface** [comment]
@zavadpe Could you have a look at this https://github.com/Stophface/react-native-maps-0.20.1/issues/10
I have no clue there...

**Comment by Stophface** [comment]
Done in 138b6409a58766ac7613d1da3c0cf5e240902de3
