### ISSUE TITLE
Java Create template files

### ISSUE THREAD

**Issue by Stophface** [Stophface/react-native-maps-0.20.1#16]
In order to implement the offline maps, files into which the code is written must be written. The files from LocalTileOverlay will be used as "template" files. In order to do this, they must be duplicated and successfully integrated into the project.

**Comment by Stophface** [comment]
In edb4f463a07d18d2af2a7ebf52528a9a2b15244e

**Comment by h3ll0w0rld123** [comment]
@Stophface I've been following your progress since it is particularly interesting to me to have a single file as opposed to multiple. However, I'm a bit confused how you didn't do a github fork of this repo? Do you intend to do a PR and get it approved back to the main repo?

**Comment by Stophface** [comment]
@h3ll0w0rld123 I am implementing `mbtiles` currently. If everything goes well, I will submit a pullrequest to the original. repo. I got `react-native-maps` and `mbtiles` working on `iOS` already. Currently I am working on the Android (`Java`) implementation (which is a bit more tricky). Your welcome to help :-)

I am not sure if I understand you correctly? I forked the repo (release version 0.20.1).
See here for the reason (https://github.com/Stophface/maps)

**Comment by h3ll0w0rld123** [comment]
Hmm, from your repo it looks like you just created a new repo and copied the files over. [Forking a repo ](https://help.github.com/articles/fork-a-repo/) is an actual github action. e.g. https://github.com/zavadpe/react-native-maps has 
<img width="357" alt="screen shot 2018-04-01 at 12 21 12 pm" src="https://user-images.githubusercontent.com/37881478/38172157-36268962-35a7-11e8-841d-2f516ce54810.png">

This maintains the history and allows the PR, unless I'm missing something and the game has changed a lot since I last looked ;)

**Comment by h3ll0w0rld123** [comment]
I'd love to help, but not sure how helpful I can be since I have not done iOS or Android dev either, but I can dig around and look at your approach and try to pick up some things. Have you tried talking to any react-native-maps maintainers on the approach?

**Comment by h3ll0w0rld123** [comment]
Lastly, looks like you're in Berlin? I'm actually there until tomorrow! Bummer I didn't ask you about the tech scene out here haha.

**Comment by Stophface** [comment]
@h3ll0w0rld123 You are right. I cloned the repo locally because I needed an older release, namely `v0.20.1`, in order to get it up and running with the new version of `react-native`. 
I will figure a way out how to submit the `pull request` back into the original repo :) I document the changes here well, so it shouldn't be to hard to fork the repo and add my changes. 

What are you doing here?

**Comment by h3ll0w0rld123** [comment]
Hmm, couldn't you have forked it, then branched off of the v0.20.1 tag?

I've been here for a month, originally from the States, mostly traveling and working on my side project.

**Comment by Stophface** [comment]
@h3ll0w0rld123 Now that your saying that --  yes I could have. Haven't thought about it :-) Where do you stay here?

**Comment by h3ll0w0rld123** [comment]
I'm staying in Neukoln, and will be hacking for the rest of the day, happy to meet up at a cafe and do some hacking if you're down!

**Comment by Stophface** [comment]
@h3ll0w0rld123 Yes let's do that later on. Any preferences regarding the Café?

**Comment by h3ll0w0rld123** [comment]
Sounds good, and local's choice!

**Comment by Stophface** [comment]
@h3ll0w0rld123 Hey how, that won't work today.. I am coding myself away here and tonight I have a few things to do. Sorry...

**Comment by h3ll0w0rld123** [comment]
No worries dude, good luck!
